/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import DAO.Informacoes;
import DAO.UsuarioDAO;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.util.Random;
import javax.swing.JOptionPane;
import modelDominio.Usuario;
import servico.Email;

/**
 *
 * @author Jonathan Renz
 */
public class TelaEsqueceuSenha extends javax.swing.JDialog {
    
    int codigoEmail;
    Informacoes informacoes;

    /**
     * Creates new form TelaEsqueceuSenha
     */
    public TelaEsqueceuSenha(Informacoes informacoes) {
        initComponents();
        jLCodigo.setVisible(false);
        jTFCodigo.setVisible(false);
        jBVerificaoCodigo.setVisible(false);
        jLAviso.setVisible(false);
        this.informacoes = informacoes;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLCodigo = new javax.swing.JLabel();
        jTFCodigo = new javax.swing.JTextField();
        jBVerificaoCodigo = new javax.swing.JButton();
        jLAviso = new javax.swing.JLabel();
        jTFEmailRecuperacao = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLCodigo.setText("Código:");

        jTFCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFCodigoKeyPressed(evt);
            }
        });

        jBVerificaoCodigo.setText("Verificar");
        jBVerificaoCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVerificaoCodigoActionPerformed(evt);
            }
        });

        jLAviso.setForeground(new java.awt.Color(0, 153, 51));
        jLAviso.setText("Código enviado para seu email!");

        jTFEmailRecuperacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFEmailRecuperacaoActionPerformed(evt);
            }
        });
        jTFEmailRecuperacao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFEmailRecuperacaoKeyPressed(evt);
            }
        });

        jLabel1.setText("Email:");

        jLabel2.setText("RECUPERAÇÃO DE SENHA");

        jButton1.setText("Enviar código");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(141, 141, 141))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jBVerificaoCodigo)
                        .addGap(160, 160, 160))))
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLCodigo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFEmailRecuperacao, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jTFCodigo))
                        .addContainerGap(79, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLAviso)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFEmailRecuperacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(13, 13, 13)
                .addComponent(jLAviso)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLCodigo))
                .addGap(18, 18, 18)
                .addComponent(jBVerificaoCodigo)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTFCodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFCodigoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            verificacaoCodigo();
        }
    }//GEN-LAST:event_jTFCodigoKeyPressed

    private void jBVerificaoCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVerificaoCodigoActionPerformed
        verificacaoCodigo();
    }//GEN-LAST:event_jBVerificaoCodigoActionPerformed

    private void jTFEmailRecuperacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFEmailRecuperacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFEmailRecuperacaoActionPerformed

    private void jTFEmailRecuperacaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFEmailRecuperacaoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            mandarEmail();
        }
    }//GEN-LAST:event_jTFEmailRecuperacaoKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        mandarEmail();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    public void mandarEmail() {
        try {
            String email_usuario;

            email_usuario = jTFEmailRecuperacao.getText();

            Usuario user = new Usuario(email_usuario);

            UsuarioDAO userdao = new UsuarioDAO();
            ResultSet rsusuariodao = userdao.autenticacaoEmail(user);

            if (rsusuariodao.next()) {

                informacoes = new Informacoes(user);
                informacoes.userLogado.setEmail_usuario(email_usuario);

                int numeroRecuperacao = numeroAleatorio();
                Email email = new Email("RECUPERAÇÃO DE SENHA", "Seu número de recuperação é: " + numeroRecuperacao, email_usuario);
                email.enviar();

                jLCodigo.setVisible(true);
                jTFCodigo.setVisible(true);
                jBVerificaoCodigo.setVisible(true);
                jLAviso.setVisible(true);

                verificacaoCodigo();

            } else {
                JOptionPane.showMessageDialog(null, "Digite um email cadastrado!!! ");
            }

        } catch (Exception e) {

        }
    }

    public void verificacaoCodigo() {
        String textoCodigo = jTFCodigo.getText();

        if (!textoCodigo.isEmpty()) {
            try {
                int codigoDigitado = Integer.parseInt(textoCodigo);
                if (codigoDigitado == codigoEmail) {
                    TelaTrocarSenha telatrocarsenha = new TelaTrocarSenha(informacoes);
                    telatrocarsenha.setModal(true);
                    telatrocarsenha.setVisible(true);
                    dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Erro: digite o código correto! ");
                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Erro: digite um código numérico válido! ");
            }
        } else {

        }
    }

    public int numeroAleatorio() {
        Random gerador = new Random();
        int numeroGerado = gerador.nextInt(999999);
        codigoEmail = numeroGerado;
        return numeroGerado;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBVerificaoCodigo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLAviso;
    private javax.swing.JLabel jLCodigo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTFCodigo;
    private javax.swing.JTextField jTFEmailRecuperacao;
    // End of variables declaration//GEN-END:variables
}
