/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import DAO.Informacoes;
import DAO.UsuarioDAO;
import java.sql.Connection;
import javax.swing.JOptionPane;
import modelDominio.Usuario;

/**
 *
 * @author Jonathan Renz
 */
public class TelaTrocarSenha extends javax.swing.JDialog {

    Connection conn;
    Usuario user;
    Informacoes informacoes;

    /**
     * Creates new form TelaTrocarSenha
     */
    public TelaTrocarSenha(Informacoes informacoes) {
        initComponents();
        this.informacoes = informacoes;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPFSenha = new javax.swing.JPasswordField();
        jPFSenhaRepetida = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jBTrocarSenha = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jCBMostrarSenha = new javax.swing.JCheckBox();
        jCBMostrarSenha2 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nova senha:");

        jPFSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPFSenhaActionPerformed(evt);
            }
        });

        jPFSenhaRepetida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPFSenhaRepetidaActionPerformed(evt);
            }
        });

        jLabel2.setText("Digite novamente:");

        jBTrocarSenha.setText("Trocar");
        jBTrocarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTrocarSenhaActionPerformed(evt);
            }
        });

        jLabel3.setText("ALTERAÇÃO DE SENHA:");

        jCBMostrarSenha.setText("Mostrar senha");
        jCBMostrarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBMostrarSenhaActionPerformed(evt);
            }
        });

        jCBMostrarSenha2.setText("Mostrar senha");
        jCBMostrarSenha2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBMostrarSenha2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBTrocarSenha)
                .addGap(161, 161, 161))
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jCBMostrarSenha)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPFSenha)
                            .addComponent(jPFSenhaRepetida, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE))
                        .addComponent(jCBMostrarSenha2)))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jPFSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCBMostrarSenha)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jPFSenhaRepetida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCBMostrarSenha2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jBTrocarSenha)
                .addGap(37, 37, 37))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPFSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPFSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPFSenhaActionPerformed

    private void jPFSenhaRepetidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPFSenhaRepetidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPFSenhaRepetidaActionPerformed

    private void jBTrocarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTrocarSenhaActionPerformed

        if (informacoes != null && informacoes.getUserLogado() != null) {
            if (!jPFSenha.getText().isEmpty()) {
                if (!jPFSenhaRepetida.getText().isEmpty()) {
                    if (jPFSenha.getText().equals(jPFSenhaRepetida.getText())) {

                        String senha = jPFSenha.getText();
                        String email = informacoes.getUserLogado().getEmail_usuario();

                        UsuarioDAO usuarioDao = new UsuarioDAO();
                        Usuario usuario = usuarioDao.buscarPorEmail(email);

                        if (usuario != null) {

                            usuario.setSenha_usuario(senha);

                            if (usuarioDao.trocarSenha(usuario)) {
                                JOptionPane.showMessageDialog(rootPane, "Senha alterada com sucesso!");
                                TelaLogin telaLogin = new TelaLogin();
                                telaLogin.setVisible(true);
                                dispose();
                            } else {
                                JOptionPane.showMessageDialog(rootPane, "Erro ao trocar a senha no banco de dados.");
                            }
                        } else {
                            JOptionPane.showMessageDialog(rootPane, "ERRO: Informação do usuário inválida.");
                        }
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "ERRO: As senhas digitadas não são iguais. Por favor, digite a mesma senha nos dois campos para confirmar a alteração.");
                    }
                } else {
                    JOptionPane.showMessageDialog(rootPane, "ERRO: Digite a senha novamente para confirmar.");
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "ERRO: Digite uma senha.");
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "ERRO: Informações do usuário não encontradas.");
        }
    }//GEN-LAST:event_jBTrocarSenhaActionPerformed

    private void jCBMostrarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBMostrarSenhaActionPerformed
        // TODO add your handling code here:
        if (jCBMostrarSenha.isSelected())
            jPFSenha.setEchoChar((char) 0);
        else
            jPFSenha.setEchoChar('*');
    }//GEN-LAST:event_jCBMostrarSenhaActionPerformed

    private void jCBMostrarSenha2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBMostrarSenha2ActionPerformed
        // TODO add your handling code here:
        if (jCBMostrarSenha2.isSelected())
            jPFSenhaRepetida.setEchoChar((char) 0);
        else
            jPFSenhaRepetida.setEchoChar('*');
    }//GEN-LAST:event_jCBMostrarSenha2ActionPerformed

    public void limpaCampos() {
        jPFSenha.setText("");
        jPFSenhaRepetida.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBTrocarSenha;
    private javax.swing.JCheckBox jCBMostrarSenha;
    private javax.swing.JCheckBox jCBMostrarSenha2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPFSenha;
    private javax.swing.JPasswordField jPFSenhaRepetida;
    // End of variables declaration//GEN-END:variables
}
